name: Build Flutter APK

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [ main ]
    paths:
      - 'mobile/**'

jobs:
  build:
    runs-on: ubuntu-22.04  # Use specific version instead of latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    
    - name: Install dependencies
      working-directory: ./mobile
      run: |
        flutter pub get
        dart run build_runner build --delete-conflicting-outputs
    
    - name: Build APK
      working-directory: ./mobile
      env:
        API_BASE_URL: https://splitit-backend-w856.onrender.com
        SOCKET_URL: https://splitit-backend-w856.onrender.com
      run: flutter build apk --release --dart-define=API_BASE_URL=$API_BASE_URL --dart-define=SOCKET_URL=$SOCKET_URL
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: mobile/build/app/outputs/flutter-apk/app-release.apk
